language: node_js
node_js:
- '9'
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm i typescript -g
- npm i rimraf -g
script:
- yarn
- yarn clean
- yarn compile
- ls -latR dist
- yarn pack
- tar -tvf *.tgz
before_deploy:
- git config --local user.name "DevTube Bot"
- git config --local user.email "bot@dev.tube"
- export TAG_NAME="$(date +'%Y%m%d%H%M')"
- git tag "$TAG_NAME"
deploy:
  provider: releases
  name: "$TAG_NAME"
  api_key:
    secure: ZLOTgHty0xdU/7piXavb6s7aYtXaOHqb8TMv9EunmwHaqJWXFezG8e/IS2j+wSlAT4iDVWyqlYj/tYKmDvgTn3Wn51GHzhD66leWW4FWyJzgVWftrg6h5o28T2uPKANgMuwcDnb6l+0dQhZNcezPVaBSKUsWq8bT1zFCvvTo/1VfxuadtcPGI72diNI0AGU1dwbwamCBewmfHFV/rij0enqqcgRNyquaAudhnIHGO99bdZASvbTg+Q1U0gTjxgxIn739T0TWqiQEwGRdBBexfe5w1SsbcO3CRMtktv3CMNe3c79UVzII4TjVQoBb7hooHB1fjAo7pYQQMs0uewShfTHNo9kNxWfS2fzd+WX4DqJsJuOt86AG7IjaC1l/EoTIfU3mic3RI7odyC/v6UOKejDzjx/g70Uu1uSNwGysRnpDBVjYXBzhTAGOtKIk4ev3vIaP/fAVr+LVxpPYFk7z3kRUxyjk+BNICSXQvXKawuV+NuCcCUrh/sGw0hLL1coQCAPsc+Ppcn8tVAFQJd3rI8MeO7CPRgT2n2KLpSWElxo0CTGheyq0p0m+thpx+5bi6QdNv1Zl9oy+gcCJgDNTwCZekQ8KQGRtEsLKrm0bBo3GNDmmbVzqW8xQca3x3BhfJY20IMEeMANWzjNnaLubuSQaA+CYFiNTzB1TiDDLa9k=
  file: devtube-commons-v0.1.0.tgz
  overwrite: true
  skip_cleanup: true
notifications:
  slack:
    secure: N9RpVCiydqNitOLkD9epVmLDKEaMTFFG+tf4/gwrihm16FhUwXFkAy0VbuOxyV5IOrYe7e2VxSh6bIGp1d4rL52PLz21+/0RTBrAcBPDa5dd2OwFtwbkY/dvKNz2LeAiudACxY6I8UPZDjmKG2ImDk+WrXwVj5bIKO6Ya2G7+PA0+duxa8u4voCuR3VzTB4O3YLOymQApbN0u9YDAPhh4S5bzU84cV+vP0b2fqjIo/xgE0XyrQHbl8jk33LeFfhrktK30eH7KRqB3Rff1g/Uwe7eWy+pu3pXdEirprk7Xc3hJfKXy54755qCfL195tT3XitfYxxms0/82V767hd8+btu74wkcISXslcIu+iz4WxkCWqDUsooTKBFq5Y69WXEzBVEtnPWROh6VzlM7OB46z0SBphaBfpNg3YeBCEUGXK6iowEucceLkIz9HpMNBnpUAarMSneVdqUDD0syjVe2seDI6qToZrlTnK7Ws1ff6TWYDLwFLmotjdpqosuSWyR6Ci4EY6FNitaYSUqFD8HneuiYLlVWLLz1WW9D1DVSufuJiIQENDJkALXIU6kiaFCdFFxWs1NEEmzkpiXUbXGCqJQdqBE8Yyw4kc4BO9yZPZw2uSkZ/w+9XgaXGACOAfHVoW3NytQjC47+vN9uO6OEjnN8G4b+aRWBUmDPrXZGZE=
